### ISSUE TITLE
Could you please help on how to install with `pip install git+https://github.com/mihaidusmanu/pycolmap`

### ISSUE THREAD

**Issue by GabbySuwichaya** [mihaidusmanu/pycolmap#19]
Hi @mihaidusmanu,

Thanks so much for releasing this awesome package. 
Here, I would like to kindly ask for your help on how to install your package with 

`pip install git+https://github.com/mihaidusmanu/pycolmap`

Actually, I was following the instruction of image matching toolbox in [here](https://github.com/GrumpyZhou/image-matching-toolbox/blob/main/docs/install.md). 

However, I am not sure what did I do wrong... I installed it under the `immatch` conda environment.

```
(immatch) userxxxx@userxxxx:/mnt/HDD4TB1/image-matching-toolbox$ pip install git+https://github.com/mihaidusmanu/pycolmap
```

- Also, I have tried installing your package with `pip install pycolmap` which is possible. But, as I tried to use the suggested command  `pip install git+http.....` I could not do it.... 

- Is it possible to use the pip install one as the alternative? What is the difference in using this pip command versus the pip `pip install git+http.....`. Are they the same version? 

The bugs are as follows:

```
(immatch) gabby-suwichaya@gabby-suwichaya:/mnt/HDD4TB1/image-matching-toolbox$ pip install git+https://github.com/mihaidusmanu/pycolmap
Collecting git+https://github.com/mihaidusmanu/pycolmap
  Cloning https://github.com/mihaidusmanu/pycolmap to /tmp/pip-req-build-t9plrora
  Running command git clone -q https://github.com/mihaidusmanu/pycolmap /tmp/pip-req-build-t9plrora
  Resolved https://github.com/mihaidusmanu/pycolmap to commit e3ee6a30ce0435be2ce190df6a35ff63384f9c5a
  Running command git submodule update --init --recursive -q
Building wheels for collected packages: pycolmap
  Building wheel for pycolmap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/gabby-suwichaya/anaconda3/envs/immatch/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-t9plrora/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-t9plrora/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-v72izk4x
       cwd: /tmp/pip-req-build-t9plrora/
  Complete output (143 lines):
  running bdist_wheel
  running build
  running build_ext
  ['cmake', '/tmp/pip-req-build-t9plrora', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-t9plrora/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/home/gabby-suwichaya/anaconda3/envs/immatch/bin/python3.7', '-DCMAKE_BUILD_TYPE=Release']
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is GNU 9.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
  -- Found required Ceres dependency: glog
  -- Found required Ceres dependency: gflags
  -- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
  -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options filesystem system unit_test_framework
  -- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0")
  -- Found Eigen
  --   Includes : /usr/include/eigen3
  -- Found FreeImage
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
  -- Found Glog
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
  CMake Warning (dev) at /home/gabby-suwichaya/anaconda3/share/cmake-3.18/Modules/FindOpenGL.cmake:305 (message):
    Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
    available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
    cmake_policy command to set the policy and suppress this warning.
  
    FindOpenGL found both a legacy GL library:
  
      OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
  
    and GLVND libraries for OpenGL and GLX:
  
      OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
      OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
  
    OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
    compatibility with CMake 3.10 and below the legacy GL library will be used.
  Call Stack (most recent call first):
    /usr/local/share/colmap/COLMAPConfig.cmake:103 (find_package)
    CMakeLists.txt:6 (find_package)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
  -- Found Glew
  --   Includes : /usr/include
  --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
  -- Using header-only CGAL
  -- Targetting Unix Makefiles
  -- Using /usr/bin/c++ compiler.
  -- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so
  -- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so
  -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")
  -- Boost include dirs: /usr/include
  -- Boost libraries:
  -- Using gcc version 4 or later. Adding -frounding-math
  -- Found PythonInterp: /home/gabby-suwichaya/anaconda3/envs/immatch/bin/python3.7 (found version "3.7.10")
  -- Found PythonLibs: /home/gabby-suwichaya/anaconda3/envs/immatch/lib/libpython3.7m.so
  -- Performing Test HAS_CPP14_FLAG
  -- Performing Test HAS_CPP14_FLAG - Success
  -- pybind11 v2.5.dev1
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- LTO enabled
  -- Configuring done
  CMake Warning at pybind11/tools/pybind11Tools.cmake:131 (add_library):
    Cannot generate a safe runtime search path for target pycolmap because
    files in some directories may conflict with libraries in implicit
    directories:
  
      runtime library [libgmp.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
        /home/gabby-suwichaya/anaconda3/envs/immatch/lib
      runtime library [liblapack.so.3] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
        /home/gabby-suwichaya/anaconda3/envs/immatch/lib
  
    Some of these libraries may not be found correctly.
  Call Stack (most recent call first):
    CMakeLists.txt:12 (pybind11_add_module)
  
  
  -- Generating done
  -- Build files have been written to: /tmp/pip-req-build-t9plrora/build/temp.linux-x86_64-3.7
  Scanning dependencies of target pycolmap
  [ 50%] Building CXX object CMakeFiles/pycolmap.dir/main.cc.o
  In file included from /tmp/pip-req-build-t9plrora/main.cc:6:
  /tmp/pip-req-build-t9plrora/generalized_absolute_pose.cc: In function ‘pybind11::dict rig_absolute_pose_estimation(std::vector<std::vector<Eigen::Matrix<double, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1> > > >, std::vector<std::vector<Eigen::Matrix<double, 3, 1> > >, std::vector<pybind11::dict>, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > >, std::vector<Eigen::Matrix<double, 3, 1> >, double)’:
  /tmp/pip-req-build-t9plrora/generalized_absolute_pose.cc:263:22: error: ‘class colmap::GP3PEstimator’ has no member named ‘residual_type’
    263 |     ransac.estimator.residual_type = GP3PEstimator::ResidualType::ReprojectionError;
        |                      ^~~~~~~~~~~~~
  /tmp/pip-req-build-t9plrora/generalized_absolute_pose.cc:263:53: error: ‘colmap::GP3PEstimator::ResidualType’ has not been declared
    263 |     ransac.estimator.residual_type = GP3PEstimator::ResidualType::ReprojectionError;
        |                                                     ^~~~~~~~~~~~
  make[2]: *** [CMakeFiles/pycolmap.dir/build.make:82: CMakeFiles/pycolmap.dir/main.cc.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/pycolmap.dir/all] Error 2
  make: *** [Makefile:103: all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-t9plrora/setup.py", line 77, in <module>
      zip_safe=False,
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-t9plrora/setup.py", line 32, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-t9plrora/setup.py", line 66, in build_extension
      subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
    File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for pycolmap
  Running setup.py clean for pycolmap
Failed to build pycolmap
Installing collected packages: pycolmap
    Running setup.py install for pycolmap ... error
    ERROR: Command errored out with exit status 1:
     command: /home/gabby-suwichaya/anaconda3/envs/immatch/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-t9plrora/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-t9plrora/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k0kleznn/install-record.txt --single-version-externally-managed --compile --install-headers /home/gabby-suwichaya/anaconda3/envs/immatch/include/python3.7m/pycolmap
         cwd: /tmp/pip-req-build-t9plrora/
    Complete output (145 lines):
    running install
    running build
    running build_ext
    ['cmake', '/tmp/pip-req-build-t9plrora', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-t9plrora/build/lib.linux-x86_64-3.7', '-DPYTHON_EXECUTABLE=/home/gabby-suwichaya/anaconda3/envs/immatch/bin/python3.7', '-DCMAKE_BUILD_TYPE=Release']
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
    -- Found required Ceres dependency: glog
    -- Found required Ceres dependency: gflags
    -- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
    -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: program_options filesystem system unit_test_framework
    -- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0")
    -- Found Eigen
    --   Includes : /usr/include/eigen3
    -- Found FreeImage
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
    -- Found Glog
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libglog.so
    CMake Warning (dev) at /home/gabby-suwichaya/anaconda3/share/cmake-3.18/Modules/FindOpenGL.cmake:305 (message):
      Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
      available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.
    
      FindOpenGL found both a legacy GL library:
    
        OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
    
      and GLVND libraries for OpenGL and GLX:
    
        OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
        OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
    
      OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
      compatibility with CMake 3.10 and below the legacy GL library will be used.
    Call Stack (most recent call first):
      /usr/local/share/colmap/COLMAPConfig.cmake:103 (find_package)
      CMakeLists.txt:6 (find_package)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    -- Found Glew
    --   Includes : /usr/include
    --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
    -- Using header-only CGAL
    -- Targetting Unix Makefiles
    -- Using /usr/bin/c++ compiler.
    -- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so
    -- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so
    -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")
    -- Boost include dirs: /usr/include
    -- Boost libraries:
    -- Using gcc version 4 or later. Adding -frounding-math
    -- Found PythonInterp: /home/gabby-suwichaya/anaconda3/envs/immatch/bin/python3.7 (found version "3.7.10")
    -- Found PythonLibs: /home/gabby-suwichaya/anaconda3/envs/immatch/lib/libpython3.7m.so
    -- Performing Test HAS_CPP14_FLAG
    -- Performing Test HAS_CPP14_FLAG - Success
    -- pybind11 v2.5.dev1
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    -- Configuring done
    CMake Warning at pybind11/tools/pybind11Tools.cmake:131 (add_library):
      Cannot generate a safe runtime search path for target pycolmap because
      files in some directories may conflict with libraries in implicit
      directories:
    
        runtime library [libgmp.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
          /home/gabby-suwichaya/anaconda3/envs/immatch/lib
        runtime library [liblapack.so.3] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
          /home/gabby-suwichaya/anaconda3/envs/immatch/lib
    
      Some of these libraries may not be found correctly.
    Call Stack (most recent call first):
      CMakeLists.txt:12 (pybind11_add_module)
    
    
    -- Generating done
    -- Build files have been written to: /tmp/pip-req-build-t9plrora/build/temp.linux-x86_64-3.7
    Scanning dependencies of target pycolmap
    [ 50%] Building CXX object CMakeFiles/pycolmap.dir/main.cc.o
    In file included from /tmp/pip-req-build-t9plrora/main.cc:6:
    /tmp/pip-req-build-t9plrora/generalized_absolute_pose.cc: In function ‘pybind11::dict rig_absolute_pose_estimation(std::vector<std::vector<Eigen::Matrix<double, 2, 1>, std::allocator<Eigen::Matrix<double, 2, 1> > > >, std::vector<std::vector<Eigen::Matrix<double, 3, 1> > >, std::vector<pybind11::dict>, std::vector<Eigen::Matrix<double, 4, 1>, std::allocator<Eigen::Matrix<double, 4, 1> > >, std::vector<Eigen::Matrix<double, 3, 1> >, double)’:
    /tmp/pip-req-build-t9plrora/generalized_absolute_pose.cc:263:22: error: ‘class colmap::GP3PEstimator’ has no member named ‘residual_type’
      263 |     ransac.estimator.residual_type = GP3PEstimator::ResidualType::ReprojectionError;
          |                      ^~~~~~~~~~~~~
    /tmp/pip-req-build-t9plrora/generalized_absolute_pose.cc:263:53: error: ‘colmap::GP3PEstimator::ResidualType’ has not been declared
      263 |     ransac.estimator.residual_type = GP3PEstimator::ResidualType::ReprojectionError;
          |                                                     ^~~~~~~~~~~~
    make[2]: *** [CMakeFiles/pycolmap.dir/build.make:82: CMakeFiles/pycolmap.dir/main.cc.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/pycolmap.dir/all] Error 2
    make: *** [Makefile:103: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-t9plrora/setup.py", line 77, in <module>
        zip_safe=False,
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-t9plrora/setup.py", line 32, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-t9plrora/setup.py", line 66, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/home/gabby-suwichaya/anaconda3/envs/immatch/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/gabby-suwichaya/anaconda3/envs/immatch/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-t9plrora/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-t9plrora/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k0kleznn/install-record.txt --single-version-externally-managed --compile --install-headers /home/gabby-suwichaya/anaconda3/envs/immatch/include/python3.7m/pycolmap Check the logs for full command output.

```

**Comment by mihaidusmanu** [comment]
Hello. After a recent commit, PyCOLMAP requires some recent changes from the colmap dev branch. Please refer to the following comment for more details https://github.com/mihaidusmanu/pycolmap/issues/15#issuecomment-905709176.

**Comment by GabbySuwichaya** [comment]
Hi! @mihaidusmanu, 
Thanks for your quick reply. I am so sorry for my slow response. 
I might not truly understand the conversation. 
So, I can install it with ... Is that correct ? 
`pip install git+https://github.com/mihaidusmanu/pycolmap@fe5b30345d5de31f9376675c68f19348149426b0`

**Comment by mihaidusmanu** [comment]
Hello. It depends if you want to take advantage of some of the latest changes or not.

If you do, then you'll need to first install the **latest dev version of COLMAP** and then you should be able to run `pip install git+https://github.com/mihaidusmanu/pycolmap` without issues.

If you want to use a earlier verison of PyCOLMAP with a previous COLMAP version, then you can run `pip install git+https://github.com/mihaidusmanu/pycolmap@fe5b30345d5de31f9376675c68f19348149426b0`.

**Comment by zr19980402** [comment]
could I ASK another question? I have meet the same problem on the WINDOWS, but I cannot solve it by the same way.
