### ISSUE TITLE
Install pycolmap error:` Could not find a package configuration file provided by "COLMAP" with any of the following names:`

### ISSUE THREAD

**Issue by shliang0603** [mihaidusmanu/pycolmap#5]
@mihaidusmanu Hi, I install the pycolmap in Ubuntu18.04. However, the following mistakes occurred in the process of installation. Now I do not know how to solve this problem. Could you please give me some suggestions

```python
(base) shl@zhihui-mint:~/shl_res/pycolmap$ pip install ./
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing /home/shl/shl_res/pycolmap
Building wheels for collected packages: pycolmap
  Building wheel for pycolmap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/shl/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8w46f1k6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8w46f1k6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-koabs48h
       cwd: /tmp/pip-req-build-8w46f1k6/
  Complete output (37 lines):
  running bdist_wheel
  running build
  running build_ext
  ['cmake', '/tmp/pip-req-build-8w46f1k6', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-8w46f1k6/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/shl/anaconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release']
  CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-8w46f1k6/build/temp.linux-x86_64-3.8/CMakeCache.txt is different than the directory /home/shl/shl_res/pycolmap/build/temp.linux-x86_64-3.8 where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  CMake Error: The source "/tmp/pip-req-build-8w46f1k6/CMakeLists.txt" does not match the source "/home/shl/shl_res/pycolmap/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-8w46f1k6/setup.py", line 62, in <module>
      setup(
    File "/home/shl/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "/home/shl/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/shl/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/shl/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/shl/anaconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/shl/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/shl/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/shl/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/shl/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/shl/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-8w46f1k6/setup.py", line 32, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-8w46f1k6/setup.py", line 59, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/home/shl/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-8w46f1k6', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-8w46f1k6/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/shl/anaconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pycolmap
  Running setup.py clean for pycolmap
Failed to build pycolmap
Installing collected packages: pycolmap
    Running setup.py install for pycolmap ... error
    ERROR: Command errored out with exit status 1:
     command: /home/shl/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8w46f1k6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8w46f1k6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uj1mpfls/install-record.txt --single-version-externally-managed --compile --install-headers /home/shl/anaconda3/include/python3.8/pycolmap
         cwd: /tmp/pip-req-build-8w46f1k6/
    Complete output (70 lines):
    running install
    running build
    running build_ext
    ['cmake', '/tmp/pip-req-build-8w46f1k6', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-8w46f1k6/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/shl/anaconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release']
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:6 (find_package):
      By not providing "FindCOLMAP.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "COLMAP", but
      CMake did not find one.
    
      Could not find a package configuration file provided by "COLMAP" with any
      of the following names:
    
        COLMAPConfig.cmake
        colmap-config.cmake
    
      Add the installation prefix of "COLMAP" to CMAKE_PREFIX_PATH or set
      "COLMAP_DIR" to a directory containing one of the above files.  If "COLMAP"
      provides a separate development package or SDK, be sure it has been
      installed.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-8w46f1k6/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-8w46f1k6/setup.py", line 62, in <module>
        setup(
      File "/home/shl/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/home/shl/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/shl/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/shl/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/shl/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/shl/anaconda3/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/shl/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/shl/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/shl/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/shl/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/shl/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-8w46f1k6/setup.py", line 32, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-8w46f1k6/setup.py", line 59, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/home/shl/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-8w46f1k6', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-8w46f1k6/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/shl/anaconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/shl/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8w46f1k6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8w46f1k6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uj1mpfls/install-record.txt --single-version-externally-managed --compile --install-headers /home/shl/anaconda3/include/python3.8/pycolmap Check the logs for full command output.
(base) shl@zhihui-mint:~/shl_res/pycolmap$ 
```

**Comment by mihaidusmanu** [comment]
As mentioned in the readme, COLMAP needs to be installed as a library system-wide. Please check out https://colmap.github.io/install.html#build-from-source (notably the `sudo make install` part). In case you do not have sudo access / do not wish to install COLMAP as a system-wide library, you can instead point `COLMAP_DIR` to a local installation of COLMAP (e.g. `/PATH-TO-COLMAP/build`).

**Comment by ZZWang21** [comment]
> As mentioned in the readme, COLMAP needs to be installed as a library system-wide. Please check out https://colmap.github.io/install.html#build-from-source (notably the `sudo make install` part). In case you do not have sudo access / do not wish to install COLMAP as a system-wide library, you can instead point `COLMAP_DIR` to a local installation of COLMAP (e.g. `/PATH-TO-COLMAP/build`).

I have installed COLMAP. but still got the same error.

**Comment by ZZWang21** [comment]
could @shliang0603  @mihaidusmanu  help me out? Thank you.
